language: node_js

node_js:
- '6'

matrix:
  fast_finish: true

dist: trusty

sudo: required

cache:
  yarn: true

script:
- npm run -s ci
- npm run package:osx && npm run installer:osx
- npm run package:linux && npm run installer:linux

os: osx

deploy:
  provider: releases
  api_key: todo
  file:
  - dist/NodeDB.dmg
  - dist/NodeDB-*.rpm
  - dist/NodeDB-*.deb
  skip_cleanup: true
  on:
    repo: nodedb/core
    tags: true
