language: node_js

node_js:
- '6'

matrix:
  fast_finish: true

dist: trusty

sudo: required

cache:
  yarn: true

script:
- npm run -s ci
- npm run package:osx && npm run installer:osx

os: osx

deploy:
  provider: releases
  api_key: todo
  file:
  - dist/armv7l.tar.gz
  - dist/osx.tar.gz
  - dist/linux32.tar.gz
  - dist/linux64.tar.gz
  - dist/win32.zip
  - dist/win64.zip
  skip_cleanup: true
  on:
    repo: nodedb/core
    tags: true
